# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3c2c2add506852b4a7cd639b1ad32ef00324142ab811997278af3390c68acacb2a19acd765795d7a901b33944bd14a8caae52a9d8022b7205ad95cb7f0283ab

test:
  secret_key_base: 7ea912b16166253dd690d5d9e73416eb2680d539264c067ba75ea06d0147777e8d18f57e0e104eba3881d5b4fe48d09c70682c983e7e32667dde8595aaa5cd25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
